// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8AoCSpC0lxN6QncFOSbtWSSjx4qHz3bI',
    appId: '1:1083912253516:android:2ee27a32ef6e0acebcc4e9',
    messagingSenderId: '1083912253516',
    projectId: 'fir-social-media-app-ea479',
    storageBucket: 'fir-social-media-app-ea479.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1o2J2yfyChhG-LrnAi6g1d_6N-pJgP2A',
    appId: '1:1083912253516:ios:881c1b8d2a97d066bcc4e9',
    messagingSenderId: '1083912253516',
    projectId: 'fir-social-media-app-ea479',
    storageBucket: 'fir-social-media-app-ea479.appspot.com',
    iosClientId: '1083912253516-4a9dugkubuqk1d27lg9o2slemthkjb4g.apps.googleusercontent.com',
    iosBundleId: 'com.example.demoSocialMediaApp',
  );
}
